# Config file for automatic testing at travis-ci.org
#

language: python

python:
        - "3.6"

env:
  matrix:
    - TOXENV=py36-django20
    - TOXENV=docs
    - TOXENF=flake8-py3

install:
        - pip install tox-travis
script: 
        - tox -e $TOXENV
