version: 2
jobs:
  build:
    working_directory: ~/django-fiction-outlines
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "test_requirements.txt" }}
      - run:
          command: |
            sudo pip install --upgrade pip
            sudo pip install tox
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -e . 
            pip install -r test_requirements.txt     
      - run:
          command: |
            tox
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "test_requirements.txt" }}
          paths:
            - ".venv"
            - ".tox"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - store_artifacts:
          path: htmlcov
          destination: tr1
