# Generated by Django 2.0.4 on 2018-04-08 02:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_outlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='character',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags associated with this character. Yay, taxonomy!', through='fiction_outlines.UUIDCharacterTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='location',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags for this location.', through='fiction_outlines.UUIDLocationTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='outline',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags for the outline.', through='fiction_outlines.UUIDOutlineTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='series',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags for the series.', through='fiction_outlines.UUIDOutlineTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
