# Generated by Django 2.0.4 on 2018-04-19 16:54

from django.db import migrations
import django.utils.timezone
import fiction_outlines.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_outlines', '0003_auto_20180414_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='modified',
            field=fiction_outlines.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='arcelementnode',
            name='modified',
            field=fiction_outlines.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='modified',
            field=fiction_outlines.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='characterinstance',
            name='modified',
            field=fiction_outlines.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='modified',
            field=fiction_outlines.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='locationinstance',
            name='modified',
            field=fiction_outlines.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='outline',
            name='modified',
            field=fiction_outlines.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='modified',
            field=fiction_outlines.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='storyelementnode',
            name='modified',
            field=fiction_outlines.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
    ]
